### PR TITLE
Update, because I need them

### LINKED ISSUE #37: Wrong hook used for toolbar manipulation
The plugin currently uses `wp_before_admin_bar_render` hook for toolbar manipulation. This is a _render_ hook, that doesn't have access to `$wp_admin_bar` instance and is not meant to work with it.

The appropriate hook is `admin_bar_menu` which is explicitly documented for manipulating toolbar items and comes with `$wp_admin_bar` instance access.

### PR DESCRIPTION
**Pull request by bueltge**
I use this plugin since lot of years, but always again and again and I don't know about an alternative. 
So I update small topics and leave this code style - I mean it was the start of PSR2 ;)
I don't change many topics for modern php development part, like reducing of singletons etc. because it works and do it for me to help me to switch the language really fast inside the admin area, front-end for testing in dev-mode.

This PR should fixed #37 , #25, #27, #32

### CODE REVIEW

**Comment by franz-josef-kaiser** [comment]
I pumped the version to `1.8.0` and added a tag to the repo. Thanks a lot!

**Comment by franz-josef-kaiser** [comment]
@stephenharris Could you push this update to the wp.org repo? IIRC you had this automated somehow? 
https://wordpress.org/plugins/wcm-user-language-switcher/

**Comment by stephenharris** [comment]
Just added a GitHub actions, and added 'jenkinspress' as a contributer (an account I use for automated deployments). Failing at the moment, as I think it takes 15 minutes for .org to recognise the new contributer.

**Comment by stephenharris** [comment]
Done, any new tags on this repo should trigger a tag on wp.org. I've deployed 1.8.1 - which is just your changes @franz-josef-kaiser plus the yaml file for GitHub actions.

**Comment by franz-josef-kaiser** [comment]
Thanks, @stephenharris!
**props** @bueltge

**Pull request merged**
